### ISSUE TITLE
idiot proofing 

### ISSUE THREAD

**Issue by harrypm** [dpolitis/auto-1vyrain#2]
Note to use dd mode on rufus to write iso properly or it wont boot properly and will throw errors for windows users, also very easy to take bios back to an older version in just one command with windows aswell this video was very helpful.

https://www.youtube.com/watch?v=EoV-NxwEVOs

(PS thanks for this repo!)

**Comment by dpolitis** [comment]
This video shows only how to flash basic bios image on the first chip (8MB). This results in having different version bios base image (on first chip) and different version ME etc image on the second one. YMMV. Thanks for noticing this out anyway.
